<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMSjTomz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMSjTomz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMSjTomz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMSjTomz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMSjTomz\App_KernelDevDebugContainer([
    'container.build_hash' => 'MSjTomz',
    'container.build_id' => 'ea4d8302',
    'container.build_time' => 1701277565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMSjTomz');
